name: Lint and Typecheck

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: "https://github.com/Tanukitown/design-system"
          cache: "pnpm"
      - uses: pnpm/action-setup@v2
        with:
          version: 10.30.0
          cache: true
      - run: pnpm install
      - run: pnpm run lint
